[project]
name = "caracal-destruct"
version = "0.1.3"
description = "Batch runners for CARACal"
authors = ["sphemakh <sphemakh@gmail.com>"]
license = "MIT License"
readme = "README.rst"
requires_python = ">=3.9,<3.13"
keywords = ["Astronomy", "Slurm", "Pipelines"]

dependencies = [
    "caracal @ git+https://github.com/caracal-pipeline/caracal",
    "click>=8.1.3",
    "simple-slurm>=0.3.6",
    "omegaconf>=2.3.0",
]

[project.urls]
homepage = "https://caracal.readthedocs.io"
Repository = "https://github.com/caracal-pipeline/adestruction"
"Issue Tracker" = "https://github.com/caracal-pipeline/adestruction/issues"

[tool.hatch.build.targets.sdist]
include = ["caracal_destruct"]

[tool.hatch.build.targets.wheel]
include = ["caracal_destruct"]

[project.scripts]
caracal-destruct = "caracal_destruct.main:driver"

[dependency-groups]
ruff = [
    "pre-commit>=4.3.0",
    "ruff>=0.12.9",
]

tests = [
    "pytest>=7.1.3,<8.0",
    {include-group = "ruff"},
]

dev = [
    "jupyter",
    "matplotlib",
    {include-group = "ruff"},
]
